### ISSUE TITLE
Please add the library to stackage

### ISSUE THREAD

**Issue by iustin** [kowainik/shortcut-links#18]
Per the subject, this would be useful to remove the need for pinning specific versions from hackage. Thanks!

**Comment by vrom911** [comment]
We did add it to Stackage: https://github.com/commercialhaskell/stackage/blob/9969cca46dfb94674f3124b9650159568543ba82/build-constraints.yaml#L3750

Seems like it was somehow removed without any notice.
Need to investigate what is the reason and when/how it did happen 🤔

**Comment by vrom911** [comment]
Created this PR to Stackage: https://github.com/commercialhaskell/stackage/pull/5845

**Comment by iustin** [comment]
Thanks for the fast response!

**Comment by vrom911** [comment]
Good news! `shortcut-links-0.5.1.1` (the newest one) is already on nightly: https://www.stackage.org/nightly-2021-01-28/package/shortcut-links-0.5.1.1

So I think this issue is resolved. Let me know if you still have issues with the package 🙂
